"""Add ProductModel

Revision ID: e2483e3b9359
Revises: 35c6ea5320d9
Create Date: 2023-03-23 17:31:04.889297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2483e3b9359'
down_revision = '35c6ea5320d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('purchase_status', sa.Enum('listed', 'pending', 'rejected', 'completed', name='purchasestate'), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('admins', 'username',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('sellers', 'username',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('sellers', 'username',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('admins', 'username',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_table('products')
    # ### end Alembic commands ###
